/**
 * Curated buck-converter component catalogs.
 *
 * Values are a reviewed snapshot assembled from public vendor datasheets and
 * selection guides (TI, MPS, XLSEMI, Würth, Coilcraft, Murata, TDK, Vishay).
 * They are intentionally conservative and MUST be re-verified against the
 * current datasheet before ordering hardware — the UI shows this note on every
 * result. Nothing here is generated by a model.
 */
import type { IcCatalogEntry, PassiveSelection } from './types';

export interface InductorPart {
  part: string;
  vendor: string;
  inductanceH: number;
  isatA: number;
  irmsA: number;
  dcrOhm: number;
  sizeMm: string;
  note: string;
}

export interface CapacitorPart {
  part: string;
  vendor: string;
  capacitanceF: number;
  voltageV: number;
  dielectric: string;
  packageName: string;
  /** Fraction of nominal capacitance remaining at the rated voltage (curated). */
  effectiveAtRatedBias: number;
  esrOhm: number;
  rippleCurrentA: number;
  note: string;
}

export interface DiodePart {
  part: string;
  vendor: string;
  vrV: number;
  ifA: number;
  vfV: number;
  packageName: string;
  note: string;
}

export const BUCK_ICS: IcCatalogEntry[] = [
  {
    part: 'TPS54360',
    vendor: 'Texas Instruments',
    inputMinV: 4.5,
    inputMaxV: 60,
    ioutMaxA: 3.5,
    fswMinHz: 100_000,
    fswMaxHz: 2_500_000,
    vrefV: 0.8,
    topology: 'non-synchronous',
    integratedSwitch: true,
    rdsOnHighMilliohm: 92,
    rdsOnLowMilliohm: null,
    switchDropV: null,
    gateChargeNc: 3,
    errorAmpGmMicroSiemens: 1000,
    packageName: 'SOIC-8 (DDA)',
    datasheetUrl: 'https://www.ti.com/lit/ds/symlink/tps54360.pdf',
    features: ['4.5–60 V input', '3.5 A switch', 'Adjustable 100 kHz–2.5 MHz', 'Current-mode control', 'External compensation'],
    sourceNote: 'Curated from the TPS54360 datasheet design procedure.',
  },
  {
    part: 'TPS54340',
    vendor: 'Texas Instruments',
    inputMinV: 4.5,
    inputMaxV: 42,
    ioutMaxA: 3.5,
    fswMinHz: 100_000,
    fswMaxHz: 2_500_000,
    vrefV: 0.8,
    topology: 'non-synchronous',
    integratedSwitch: true,
    rdsOnHighMilliohm: 92,
    rdsOnLowMilliohm: null,
    switchDropV: null,
    gateChargeNc: 3,
    errorAmpGmMicroSiemens: 1000,
    packageName: 'SOIC-8 (DDA)',
    datasheetUrl: 'https://www.ti.com/lit/ds/symlink/tps54340.pdf',
    features: ['4.5–42 V input', '3.5 A switch', 'Adjustable frequency', 'Current-mode control'],
    sourceNote: 'Curated from the TPS54340 datasheet design procedure.',
  },
  {
    part: 'TPS54331',
    vendor: 'Texas Instruments',
    inputMinV: 3.5,
    inputMaxV: 28,
    ioutMaxA: 3,
    fswMinHz: 570_000,
    fswMaxHz: 570_000,
    vrefV: 0.8,
    topology: 'non-synchronous',
    integratedSwitch: true,
    rdsOnHighMilliohm: 80,
    rdsOnLowMilliohm: null,
    switchDropV: null,
    gateChargeNc: 2,
    errorAmpGmMicroSiemens: 1100,
    packageName: 'SOIC-8 (D)',
    datasheetUrl: 'https://www.ti.com/lit/ds/symlink/tps54331.pdf',
    features: ['3.5–28 V input', '3 A switch', '570 kHz fixed', 'Current-mode control'],
    sourceNote: 'Curated from the TPS54331 datasheet.',
  },
  {
    part: 'LMR33630',
    vendor: 'Texas Instruments',
    inputMinV: 3.8,
    inputMaxV: 36,
    ioutMaxA: 3,
    fswMinHz: 400_000,
    fswMaxHz: 2_100_000,
    vrefV: 1,
    topology: 'synchronous',
    integratedSwitch: true,
    rdsOnHighMilliohm: 130,
    rdsOnLowMilliohm: 85,
    switchDropV: null,
    gateChargeNc: 2,
    errorAmpGmMicroSiemens: 1500,
    packageName: 'HSOIC-8',
    datasheetUrl: 'https://www.ti.com/lit/ds/symlink/lmr33630.pdf',
    features: ['3.8–36 V input', '3 A synchronous', '400 kHz / 1.4 MHz / 2.1 MHz options', 'Low EMI'],
    sourceNote: 'Curated from the LMR33630 datasheet.',
  },
  {
    part: 'TPS563201',
    vendor: 'Texas Instruments',
    inputMinV: 4.5,
    inputMaxV: 17,
    ioutMaxA: 3,
    fswMinHz: 580_000,
    fswMaxHz: 580_000,
    vrefV: 0.768,
    topology: 'synchronous',
    integratedSwitch: true,
    rdsOnHighMilliohm: 80,
    rdsOnLowMilliohm: 45,
    switchDropV: null,
    gateChargeNc: 1.5,
    errorAmpGmMicroSiemens: 1300,
    packageName: 'SOT-23-6',
    datasheetUrl: 'https://www.ti.com/lit/ds/symlink/tps563201.pdf',
    features: ['4.5–17 V input', '3 A synchronous', '580 kHz fixed', 'Internal compensation'],
    sourceNote: 'Curated from the TPS563201 datasheet.',
  },
  {
    part: 'TPS62130',
    vendor: 'Texas Instruments',
    inputMinV: 3,
    inputMaxV: 17,
    ioutMaxA: 3,
    fswMinHz: 2_500_000,
    fswMaxHz: 2_500_000,
    vrefV: 0.8,
    topology: 'synchronous',
    integratedSwitch: true,
    rdsOnHighMilliohm: 30,
    rdsOnLowMilliohm: 25,
    switchDropV: null,
    gateChargeNc: 1,
    errorAmpGmMicroSiemens: 1500,
    packageName: 'VQFN-16',
    datasheetUrl: 'https://www.ti.com/lit/ds/symlink/tps62130.pdf',
    features: ['3–17 V input', '3 A synchronous', '2.5 MHz', 'Small solution size'],
    sourceNote: 'Curated from the TPS62130 datasheet.',
  },
  {
    part: 'TPS62933',
    vendor: 'Texas Instruments',
    inputMinV: 3.8,
    inputMaxV: 30,
    ioutMaxA: 3,
    fswMinHz: 200_000,
    fswMaxHz: 2_200_000,
    vrefV: 0.8,
    topology: 'synchronous',
    integratedSwitch: true,
    rdsOnHighMilliohm: 80,
    rdsOnLowMilliohm: 40,
    switchDropV: null,
    gateChargeNc: 2,
    errorAmpGmMicroSiemens: 1400,
    packageName: 'SOT-583',
    datasheetUrl: 'https://www.ti.com/lit/ds/symlink/tps62933.pdf',
    features: ['3.8–30 V input', '3 A synchronous', '200 kHz–2.2 MHz adjustable'],
    sourceNote: 'Curated from the TPS62933 datasheet.',
  },
  {
    part: 'LM2596',
    vendor: 'Texas Instruments',
    inputMinV: 4.5,
    inputMaxV: 40,
    ioutMaxA: 3,
    fswMinHz: 150_000,
    fswMaxHz: 150_000,
    vrefV: 1.23,
    topology: 'non-synchronous',
    integratedSwitch: true,
    rdsOnHighMilliohm: null,
    rdsOnLowMilliohm: null,
    switchDropV: 1.2,
    gateChargeNc: null,
    errorAmpGmMicroSiemens: 1000,
    packageName: 'TO-220 / TO-263',
    datasheetUrl: 'https://www.ti.com/lit/ds/symlink/lm2596.pdf',
    features: ['4.5–40 V input', '3 A', '150 kHz', 'Classic low-cost buck'],
    sourceNote: 'Curated from the LM2596 datasheet; bipolar switch modeled as a 1.2 V drop.',
  },
  {
    part: 'MP1584',
    vendor: 'Monolithic Power Systems',
    inputMinV: 4.5,
    inputMaxV: 28,
    ioutMaxA: 3,
    fswMinHz: 100_000,
    fswMaxHz: 1_500_000,
    vrefV: 0.8,
    topology: 'non-synchronous',
    integratedSwitch: true,
    rdsOnHighMilliohm: 150,
    rdsOnLowMilliohm: null,
    switchDropV: null,
    gateChargeNc: 2,
    errorAmpGmMicroSiemens: 800,
    packageName: 'SOIC-8E',
    datasheetUrl: 'https://www.monolithicpower.com/en/mp1584.html',
    features: ['4.5–28 V input', '3 A', 'Adjustable 100 kHz–1.5 MHz'],
    sourceNote: 'Curated from the MP1584 datasheet.',
  },
  {
    part: 'XL4015',
    vendor: 'XLSEMI',
    inputMinV: 8,
    inputMaxV: 36,
    ioutMaxA: 5,
    fswMinHz: 180_000,
    fswMaxHz: 180_000,
    vrefV: 1.25,
    topology: 'non-synchronous',
    integratedSwitch: true,
    rdsOnHighMilliohm: null,
    rdsOnLowMilliohm: null,
    switchDropV: 1.0,
    gateChargeNc: null,
    errorAmpGmMicroSiemens: 1000,
    packageName: 'TO-263-5',
    datasheetUrl: 'https://www.xlsemi.com/datasheet/XL4015%20datasheet.pdf',
    features: ['8–36 V input', '5 A', '180 kHz', 'Low-cost modules'],
    sourceNote: 'Curated from the XL4015 datasheet; bipolar switch modeled as a 1.0 V drop.',
  },
];

export const INDUCTORS: InductorPart[] = [
  { part: '744774047', vendor: 'Würth Elektronik', inductanceH: 4.7e-6, isatA: 4.6, irmsA: 4.4, dcrOhm: 0.027, sizeMm: '7.3×7.3×4.5', note: 'Shielded drum core.' },
  { part: '744774068', vendor: 'Würth Elektronik', inductanceH: 6.8e-6, isatA: 4.0, irmsA: 3.8, dcrOhm: 0.035, sizeMm: '7.3×7.3×4.5', note: 'Shielded drum core.' },
  { part: '744774110', vendor: 'Würth Elektronik', inductanceH: 10e-6, isatA: 3.4, irmsA: 3.2, dcrOhm: 0.05, sizeMm: '7.3×7.3×4.5', note: 'Shielded drum core.' },
  { part: 'XAL5030-472MEB', vendor: 'Coilcraft', inductanceH: 4.7e-6, isatA: 11.3, irmsA: 8.0, dcrOhm: 0.0126, sizeMm: '5.5×5.3×5.0', note: 'High-current molded.' },
  { part: 'XAL7050-103MEB', vendor: 'Coilcraft', inductanceH: 10e-6, isatA: 9.0, irmsA: 7.0, dcrOhm: 0.02, sizeMm: '7.2×6.6×5.0', note: 'High-current molded.' },
  { part: 'SRP1245A-100M', vendor: 'Bourns', inductanceH: 10e-6, isatA: 10.0, irmsA: 8.5, dcrOhm: 0.022, sizeMm: '12.5×12.5×4.5', note: 'Shielded, AEC-Q200.' },
  { part: 'XAL7050-223MEB', vendor: 'Coilcraft', inductanceH: 22e-6, isatA: 4.5, irmsA: 3.5, dcrOhm: 0.055, sizeMm: '7.2×6.6×5.0', note: 'High-current molded.' },
  { part: '744774122', vendor: 'Würth Elektronik', inductanceH: 22e-6, isatA: 2.4, irmsA: 2.1, dcrOhm: 0.09, sizeMm: '7.3×7.3×4.5', note: 'Shielded drum core.' },
  { part: 'SRP1038A-220M', vendor: 'Bourns', inductanceH: 22e-6, isatA: 5.0, irmsA: 4.0, dcrOhm: 0.06, sizeMm: '10.3×10.3×3.8', note: 'Shielded, AEC-Q200.' },
  { part: '744774133', vendor: 'Würth Elektronik', inductanceH: 33e-6, isatA: 1.9, irmsA: 1.7, dcrOhm: 0.13, sizeMm: '7.3×7.3×4.5', note: 'Shielded drum core.' },
  { part: '744774147', vendor: 'Würth Elektronik', inductanceH: 47e-6, isatA: 1.6, irmsA: 1.4, dcrOhm: 0.18, sizeMm: '7.3×7.3×4.5', note: 'Shielded drum core.' },
];

export const CAPACITORS: CapacitorPart[] = [
  { part: 'GRM32ER61E226KE15', vendor: 'Murata', capacitanceF: 22e-6, voltageV: 25, dielectric: 'X5R', packageName: '1210', effectiveAtRatedBias: 0.55, esrOhm: 0.003, rippleCurrentA: 3.0, note: 'Effective capacitance falls with DC bias; verify in the vendor tool.' },
  { part: 'C3216X7R1E106K160AB', vendor: 'TDK', capacitanceF: 10e-6, voltageV: 25, dielectric: 'X7R', packageName: '1206', effectiveAtRatedBias: 0.6, esrOhm: 0.004, rippleCurrentA: 2.0, note: 'X7R bias derating is significant above 12 V.' },
  { part: 'GRM31CR61A476ME15', vendor: 'Murata', capacitanceF: 47e-6, voltageV: 10, dielectric: 'X5R', packageName: '1206', effectiveAtRatedBias: 0.5, esrOhm: 0.002, rippleCurrentA: 4.0, note: 'Only usable when vinMax is comfortably below the rating.' },
  { part: 'GRM32ER60J107ME20', vendor: 'Murata', capacitanceF: 100e-6, voltageV: 6.3, dielectric: 'X5R', packageName: '1210', effectiveAtRatedBias: 0.45, esrOhm: 0.0015, rippleCurrentA: 5.0, note: 'Low-voltage rail bulk.' },
  { part: 'C1210X7S0J226M', vendor: 'TDK', capacitanceF: 22e-6, voltageV: 6.3, dielectric: 'X7S', packageName: '1210', effectiveAtRatedBias: 0.5, esrOhm: 0.002, rippleCurrentA: 4.0, note: 'Output-side low-voltage capacitor.' },
];

export const DIODES: DiodePart[] = [
  { part: 'SS34', vendor: 'Vishay', vrV: 40, ifA: 3, vfV: 0.5, packageName: 'SMA', note: 'Common Schottky rectifier.' },
  { part: 'B540C', vendor: 'Diodes Inc.', vrV: 40, ifA: 5, vfV: 0.55, packageName: 'SMC', note: 'Higher-current Schottky.' },
  { part: 'SBR3U40P1', vendor: 'Diodes Inc.', vrV: 40, ifA: 3, vfV: 0.47, packageName: 'PowerDI5', note: 'Low-Vf SBR.' },
  { part: 'PDS760', vendor: 'Diodes Inc.', vrV: 60, ifA: 7, vfV: 0.52, packageName: 'PowerDI5', note: '60 V for higher input rails.' },
];

/** E96 preferred values used for feedback dividers. */
export const E96_BASE: number[] = [
  100, 102, 105, 107, 110, 113, 115, 118, 121, 124, 127, 130, 133, 137, 140, 143, 147, 150, 154, 158, 162, 165, 169, 174,
  178, 182, 187, 191, 196, 200, 205, 210, 215, 221, 226, 232, 237, 243, 249, 255, 261, 267, 274, 280, 287, 294, 301,
  309, 316, 324, 332, 340, 348, 357, 365, 374, 383, 392, 402, 412, 422, 432, 442, 453, 464, 475, 487, 499, 511, 523,
  536, 549, 562, 576, 590, 604, 619, 634, 649, 665, 681, 698, 715, 732, 750, 768, 787, 806, 825, 845, 866, 887, 909, 931, 953, 976,
];

/** Nearest E96 value at or above the requested resistance. */
export function nearestE96(ohm: number, decade?: number): number {
  const exponent = decade ?? Math.floor(Math.log10(ohm)) - 2;
  const scaled = ohm / 10 ** exponent;
  const candidate = E96_BASE.find((value) => value >= scaled) ?? E96_BASE[E96_BASE.length - 1];
  return candidate * 10 ** exponent;
}

export function toSelection(kind: PassiveSelection['kind'], part: { part: string; vendor: string }, value: string, rated: string, keyParams: Record<string, string>, reason: string): PassiveSelection {
  return { kind, part: part.part, vendor: part.vendor, value, rated, keyParams, reason };
}
