/**
 * OpenLane-style layout export.
 *
 * Converts an in-memory `OpenlaneLayout` into the two text artifacts that
 * OpenLane produces at signoff:
 *
 *   - A DEF file (Design Exchange Format) — the canonical textual layout.
 *   - A text-GDS (GDSII is binary in real OpenLane; we emit a human-readable
 *     rendition with the same structural elements so users can inspect it).
 *
 * These exports are educational: real OpenLane DEFs carry pin/net metadata
 * that our simulation doesn't model. We emit the structural skeleton that
 * KLayout / gdsutils will load.
 */

import type { OpenlaneLayout } from '@/lib/db';

/** Convert nanometre-scale layout coords to DEF database units (typically 1000/µm). */
const DBU_PER_MICRON = 1000;

export function toDef(layout: OpenlaneLayout, designName: string): string {
  // Tolerate legacy runs with empty `layout = {}`.
  const chipWidth = layout?.chipWidth ?? 0;
  const chipHeight = layout?.chipHeight ?? 0;
  const cells = layout?.cells ?? [];
  const wires = layout?.wires ?? [];

  const diePts = [
    `( 0 0 )`,
    `( ${Math.round(chipWidth * DBU_PER_MICRON)} 0 )`,
    `( ${Math.round(chipWidth * DBU_PER_MICRON)} ${Math.round(chipHeight * DBU_PER_MICRON)} )`,
    `( 0 ${Math.round(chipHeight * DBU_PER_MICRON)} )`,
  ].join(' ');

  const componentLines = cells.map(c =>
    `    - ${c.id} ${c.type}\n      + PLACED ( ${Math.round(c.x * DBU_PER_MICRON)} ${Math.round(c.y * DBU_PER_MICRON)} ) N ;`,
  ).join('\n');

  // Group wires by net so we can emit one NET section per net.
  const netsMap = new Map<string, typeof wires>();
  for (const w of wires) {
    const list = netsMap.get(w.netId) ?? [];
    list.push(w);
    netsMap.set(w.netId, list);
  }
  const netLines = [...netsMap.entries()].map(([netId, wiresForNet]) => {
    const routed = wiresForNet.map(w => {
      if (w.points.length < 2) return '';
      const [p0, ...rest] = w.points;
      const segs = rest.map(p => `( ${Math.round(p.x * DBU_PER_MICRON)} ${Math.round(p.y * DBU_PER_MICRON)} )`).join(' ');
      return `      + ROUTED met${w.layer} ( ${Math.round(p0.x * DBU_PER_MICRON)} ${Math.round(p0.y * DBU_PER_MICRON)} ) ${segs}`;
    }).filter(Boolean).join('\n');
    return `    - ${netId}\n${routed} ;`;
  }).join('\n');

  return [
    `# DEF export — ${designName}`,
    `# Generated by chip-design OpenLane simulation`,
    `VERSION 5.8 ;`,
    `DIVIDERCHAR "/" ;`,
    `BUSBITCHARS "[]" ;`,
    `DESIGN ${designName} ;`,
    `UNITS DISTANCE MICRONS ${DBU_PER_MICRON} ;`,
    `DIEAREA ${diePts} ;`,
    ``,
    `COMPONENTS ${cells.length} ;`,
    componentLines,
    `END COMPONENTS`,
    ``,
    `NETS ${netsMap.size} ;`,
    netLines,
    `END NETS`,
    ``,
    `END DESIGN`,
    ``,
  ].join('\n');
}

/**
 * Emit a readable text-GDS. Real GDSII is a binary stream of records
 * (HEADER, BGNLIB, LIBNAME, UNITS, BGNSTR, STRNAME, BOUNDARY...). We print
 * the equivalent record tree in text so it matches the structure KLayout
 * would display in its GDS browser panel.
 */
export function toGds(layout: OpenlaneLayout, designName: string): string {
  const chipWidth = layout?.chipWidth ?? 0;
  const chipHeight = layout?.chipHeight ?? 0;
  const cells = layout?.cells ?? [];
  const wires = layout?.wires ?? [];
  const unit = 1e-3; // µm → m (GDS UNITS user unit)
  const dbUnit = 1e-9; // 1 nm db unit

  const lines: string[] = [];
  lines.push(`HEADER 600`);
  lines.push(`BGNLIB ${new Date().toISOString()}`);
  lines.push(`LIBNAME ${designName.toUpperCase()}_LIB`);
  lines.push(`UNITS ${unit} ${dbUnit}`);
  lines.push(`BGNSTR ${new Date().toISOString()}`);
  lines.push(`STRNAME ${designName}`);

  // Cell boundaries as BOUNDARY records on layer 0.
  for (const c of cells) {
    const x0 = Math.round(c.x * DBU_PER_MICRON);
    const y0 = Math.round(c.y * DBU_PER_MICRON);
    const x1 = Math.round((c.x + c.width) * DBU_PER_MICRON);
    const y1 = Math.round((c.y + c.height) * DBU_PER_MICRON);
    lines.push(`  BOUNDARY`);
    lines.push(`    LAYER 0  DATATYPE 0`);
    lines.push(`    XY: (${x0},${y0}) (${x1},${y0}) (${x1},${y1}) (${x0},${y1}) (${x0},${y0})`);
    lines.push(`    PROPVALUE: cell=${c.id} type=${c.type}`);
    lines.push(`  ENDEL`);
  }

  // Wires as PATH records; layer index maps to GDS metal layer.
  for (const w of wires) {
    if (w.points.length < 2) continue;
    lines.push(`  PATH`);
    lines.push(`    LAYER ${w.layer}  DATATYPE 0`);
    lines.push(`    PATHTYPE 0  WIDTH 140`);
    const xy = w.points.map(p =>
      `(${Math.round(p.x * DBU_PER_MICRON)},${Math.round(p.y * DBU_PER_MICRON)})`,
    ).join(' ');
    lines.push(`    XY: ${xy}`);
    lines.push(`    PROPVALUE: net=${w.netId}`);
    lines.push(`  ENDEL`);
  }

  lines.push(`ENDSTR`);
  lines.push(`ENDLIB`);
  lines.push(``);
  lines.push(`# Summary`);
  lines.push(`# ${cells.length} BOUNDARY records (cells)`);
  lines.push(`# ${wires.length} PATH records (wires)`);
  lines.push(`# die: ${chipWidth} µm × ${chipHeight} µm`);
  return lines.join('\n');
}
