/**
 * Verification helpers for generated RTL.
 *
 * These helpers shell out to `iverilog`/`vvp` and `yosys` when the binaries are
 * on PATH and report `available: false` otherwise, so tests and workflows can
 * skip gracefully instead of failing on machines without an EDA install.
 *
 * Everything generated by `src/lib/accelerator/systolic.ts` is
 * GENERATED RTL - REQUIRES VERIFICATION; these helpers are how that
 * verification is actually performed:
 *   * `runIcarusSimulation` compiles the design + self-checking testbench and
 *     reports PASS/FAIL from the simulation transcript.
 *   * `runYosysSynthesisCheck` elaborates + synthesises the design and returns
 *     the Yosys `stat` cell counts (or the error text if synthesis fails).
 */
import { spawn } from 'child_process';
import { promises as fs } from 'fs';
import fsSync from 'fs';
import os from 'os';
import path from 'path';

export interface IcarusRunOptions {
  /** Design (DUT) source text. */
  verilog: string;
  /** Testbench source text. */
  testbench: string;
  /** Optional extra source files. */
  extraSources?: { name: string; text: string }[];
  /** Optional extra iverilog arguments. */
  extraArgs?: string[];
  /** Wall-clock limit for each subprocess. */
  timeoutMs?: number;
  /** Keep the temporary work directory (returned as `workDir`). */
  keepWorkDir?: boolean;
}

export interface IcarusRunResult {
  available: boolean;
  binary: string | null;
  compiled: boolean;
  ran: boolean;
  /** True iff the simulation transcript contains a PASS marker and no FAIL marker. */
  pass: boolean;
  stdout: string;
  stderr: string;
  /** Human-readable commands that were executed. */
  commands: string[];
  /** Present only when `keepWorkDir` is true. */
  workDir?: string;
}

export interface YosysCheckOptions {
  verilog: string;
  top: string;
  timeoutMs?: number;
  extraCommands?: string[];
}

export interface YosysCheckResult {
  available: boolean;
  binary: string | null;
  ok: boolean;
  cellCount: number;
  cells: Record<string, number>;
  stdout: string;
  stderr: string;
  commands: string[];
}

/** Synchronous PATH scan (usable at module scope to decide `it` vs `it.skip`). */
export function findOnPathSync(exe: string): string | null {
  const searchPath = process.env.PATH;
  if (!searchPath) return null;
  for (const dir of searchPath.split(path.delimiter)) {
    if (!dir) continue;
    const full = path.join(dir, exe);
    try {
      const st = fsSync.statSync(full);
      if (st.isFile()) return full;
    } catch {
      /* try next directory */
    }
  }
  return null;
}

/** Spawn with a hard wall-clock timeout (kills the child on expiry). */
function runWithTimeout(
  bin: string,
  args: string[],
  opts: { timeoutMs: number; cwd?: string }
): Promise<{ stdout: string; stderr: string; code: number | null; timedOut: boolean }> {
  return new Promise((resolve) => {
    const child = spawn(bin, args, { stdio: ['ignore', 'pipe', 'pipe'], cwd: opts.cwd });
    let stdout = '';
    let stderr = '';
    let timedOut = false;
    const timer = setTimeout(() => {
      timedOut = true;
      child.kill('SIGKILL');
    }, Math.max(1000, opts.timeoutMs));
    child.stdout.on('data', (d) => {
      stdout += String(d);
    });
    child.stderr.on('data', (d) => {
      stderr += String(d);
    });
    child.on('error', (err) => {
      clearTimeout(timer);
      resolve({ stdout, stderr: stderr + String(err), code: null, timedOut });
    });
    child.on('close', (code) => {
      clearTimeout(timer);
      resolve({ stdout, stderr, code, timedOut });
    });
  });
}

/**
 * Compile and run a generated design against its generated testbench.
 *
 * The generated testbench is self-checking: it prints a line starting with
 * `PASS:` when the C memory matches the in-testbench reference GEMM and the
 * measured cycle count matches the closed-form model, and prints `FAIL:` lines
 * otherwise. `pass` is derived from that transcript only.
 */
export async function runIcarusSimulation(opts: IcarusRunOptions): Promise<IcarusRunResult> {
  const binary = findOnPathSync('iverilog');
  const vvpBinary = findOnPathSync('vvp');
  const base: IcarusRunResult = {
    available: binary !== null && vvpBinary !== null,
    binary,
    compiled: false,
    ran: false,
    pass: false,
    stdout: '',
    stderr: '',
    commands: [],
  };
  if (!base.available || !binary || !vvpBinary) return base;

  const timeoutMs = opts.timeoutMs ?? 30_000;
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'systolic-iverilog-'));
  try {
    const designPath = path.join(dir, 'dut.v');
    const tbPath = path.join(dir, 'tb.v');
    const outPath = path.join(dir, 'sim.vvp');
    await fs.writeFile(designPath, opts.verilog);
    await fs.writeFile(tbPath, opts.testbench);
    const sources = [tbPath, designPath];
    for (const extra of opts.extraSources ?? []) {
      const p = path.join(dir, extra.name);
      await fs.writeFile(p, extra.text);
      sources.push(p);
    }
    const compileArgs = ['-g2005', '-o', outPath, ...sources, ...(opts.extraArgs ?? [])];
    base.commands.push(`iverilog ${compileArgs.join(' ')}`);
    const compile = await runWithTimeout(binary, compileArgs, { timeoutMs });
    base.stdout += compile.stdout;
    base.stderr += compile.stderr;
    // iverilog returns 0 even with non-fatal warnings; a missing output file is
    // the reliable signal that compilation failed.
    base.compiled = !compile.timedOut && fsSync.existsSync(outPath);
    if (!base.compiled) return base;

    base.commands.push(`vvp ${outPath}`);
    const run = await runWithTimeout(vvpBinary, [outPath], { timeoutMs });
    base.ran = !run.timedOut;
    base.stdout += run.stdout;
    base.stderr += run.stderr;
    base.pass =
      base.ran &&
      /(^|\n)PASS:/.test(base.stdout) &&
      !/(^|\n)FAIL:/.test(base.stdout) &&
      compile.code === 0;
    return base;
  } finally {
    if (opts.keepWorkDir) {
      base.workDir = dir;
    } else {
      await fs.rm(dir, { recursive: true, force: true }).catch(() => {
        /* best effort */
      });
    }
  }
}

/** Structural counters that Yosys prints next to cell-type counts. */
const NON_CELL_STAT_KEYS = new Set([
  'wires',
  'wire',
  'bits',
  'ports',
  'port',
  'memories',
  'memory',
  'processes',
  'submodules',
  'cells',
]);

/**
 * Parse a Yosys `stat` block: total and per-cell counts.
 *
 * Yosys 0.68 prints `2198 cells` + `350   $_AND_` lines inside a
 * `=== module ===` section, while older releases print
 * `Number of cells: 2198` + `NAND2_X1  5` lines. Both are supported; the first
 * section is used, which is the `-top` module when the script uses `stat -top`.
 */
export function parseYosysStat(stdout: string): { cellCount: number; cells: Record<string, number> } {
  const cells: Record<string, number> = {};
  let total = 0;
  const sections = stdout.split(/^\s*===\s.*===\s*$/m);
  const body = sections.length > 1 ? sections[1] ?? '' : stdout;
  for (const raw of body.split('\n')) {
    const line = raw.trimEnd();
    const legacyHeader = line.match(/^\s*Number of cells:\s*(-?\d+)\s*$/);
    if (legacyHeader) {
      total = parseInt(legacyHeader[1], 10);
      continue;
    }
    const modernHeader = line.match(/^\s*(-?\d+)\s+cells\s*$/);
    if (modernHeader) {
      total = parseInt(modernHeader[1], 10);
      continue;
    }
    const modernCell = line.match(/^\s*(\d+)\s+(\$[A-Za-z0-9_$.\\]+|[A-Za-z_][\w$]*)\s*$/);
    if (modernCell) {
      const key = modernCell[2];
      // Yosys prints structural counters alongside cells; keep only cell types.
      if (!NON_CELL_STAT_KEYS.has(key)) cells[key] = parseInt(modernCell[1], 10);
      continue;
    }
    const legacyCell = line.match(/^\s*(\$[\w$]+|[A-Za-z_]\w*)\s+(\d+)\s*$/);
    if (legacyCell) cells[legacyCell[1]] = parseInt(legacyCell[2], 10);
  }
  return { cellCount: total, cells };
}

/**
 * Elaborate + synthesise the generated design with Yosys (`proc; opt; fsm;
 * opt; memory; opt; techmap; opt; stat`). `ok` is true only when Yosys exits 0
 * and reports at least one cell.
 */
export async function runYosysSynthesisCheck(opts: YosysCheckOptions): Promise<YosysCheckResult> {
  const binary = findOnPathSync('yosys');
  const base: YosysCheckResult = {
    available: binary !== null,
    binary,
    ok: false,
    cellCount: 0,
    cells: {},
    stdout: '',
    stderr: '',
    commands: [],
  };
  if (!binary) return base;

  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'systolic-yosys-'));
  try {
    const designPath = path.join(dir, 'dut.v');
    await fs.writeFile(designPath, opts.verilog);
    const script = [
      `read_verilog ${designPath}`,
      `hierarchy -top ${opts.top}`,
      'proc; opt',
      'fsm; opt',
      'memory; opt',
      'techmap; opt',
      `stat -top ${opts.top}`,
      ...(opts.extraCommands ?? []),
    ].join('\n');
    const scriptPath = path.join(dir, 'synth.ys');
    await fs.writeFile(scriptPath, script);
    base.commands.push(`yosys -s ${scriptPath}`);
    const run = await runWithTimeout(binary, ['-s', scriptPath], { timeoutMs: opts.timeoutMs ?? 120_000 });
    base.stdout = run.stdout;
    base.stderr = run.stderr;
    const stats = parseYosysStat(run.stdout);
    base.cellCount = stats.cellCount;
    base.cells = stats.cells;
    base.ok = run.code === 0 && !run.timedOut && stats.cellCount > 0;
    return base;
  } finally {
    await fs.rm(dir, { recursive: true, force: true }).catch(() => {
      /* best effort */
    });
  }
}
